name: Build and Deploy Crypto Analysis

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC to update crypto data
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        cd backend/data_fetcher
        pip install -r requirements.txt
    
    - name: Create data directory
      run: |
        mkdir -p backend/data
    
    - name: Test CoinGecko connectivity
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: |
        cd backend/data_fetcher
        python test_coingecko_api.py || echo "API test completed with warnings"
    
    - name: Fetch cryptocurrency data
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: |
        cd backend/data_fetcher
        python fetch_crypto_data.py
      continue-on-error: false
      timeout-minutes: 10
    
    # Critical debug step
    - name: Debug - Check where files were created
      run: |
        echo "=== Looking for all CSV and JSON files ==="
        find . -name "*.csv" -o -name "*.json" | grep -E "(combined_data|metadata|pipeline_status)" | while read file; do
          echo "Found: $file (size: $(stat -c%s "$file") bytes)"
        done
        
        echo -e "\n=== Expected location: backend/data/ ==="
        if [ -d "backend/data" ]; then
          ls -la backend/data/
        else
          echo "Directory backend/data does not exist!"
        fi
        
        echo -e "\n=== Checking if combined_data.csv exists ==="
        if [ -f "backend/data/combined_data.csv" ]; then
          echo "✓ combined_data.csv found at expected location"
          echo "First 3 lines:"
          head -3 backend/data/combined_data.csv
        else
          echo "✗ combined_data.csv NOT found at backend/data/"
        fi
    
    - name: Upload data artifacts
      uses: actions/upload-artifact@v4
      with:
        name: crypto-data
        path: backend/data/
        retention-days: 7
        if-no-files-found: error
    
    - name: Check pipeline status
      run: |
        if [ -f "backend/data/pipeline_status.json" ]; then
          echo "Pipeline status:"
          cat backend/data/pipeline_status.json | python -m json.tool
        else
          echo "No pipeline status file found"
          exit 1
        fi

  analyze-data:
    needs: fetch-data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download data artifacts
      uses: actions/download-artifact@v4
      with:
        name: crypto-data
        path: backend/data/
    
    - name: Debug - Verify downloaded files
      run: |
        echo "=== Contents of backend/data/ after artifact download ==="
        ls -la backend/data/
        
        echo -e "\n=== Verifying critical files ==="
        for file in combined_data.csv metadata.json; do
          if [ -f "backend/data/$file" ]; then
            echo "✓ $file exists (size: $(stat -c%s "backend/data/$file") bytes)"
          else
            echo "✗ $file is missing!"
            exit 1
          fi
        done
    
    - name: Set up Python for wrapper script
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies for wrapper
      run: |
        cd backend/data_fetcher
        pip install -r requirements.txt
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          backend/rust_analyzer/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Debug - Check Rust project structure
      run: |
        echo "=== Rust project location ==="
        ls -la backend/rust_analyzer/
        echo -e "\n=== Cargo.toml contents ==="
        cat backend/rust_analyzer/Cargo.toml
    
    - name: Build Rust project first
      run: |
        cd backend/rust_analyzer
        cargo build --release
    
    - name: Run Rust analyzer directly (debug)
      run: |
        echo "=== Running from backend/rust_analyzer ==="
        cd backend/rust_analyzer
        
        echo "Current directory: $(pwd)"
        echo "Looking for data in: ../data/"
        echo "Contents of ../data/:"
        ls -la ../data/ || echo "Directory not found"
        
        echo -e "\n=== Running analyzer ==="
        cargo run --release || {
          echo "=== Rust analyzer failed ==="
          echo "Check if the error mentions missing files"
          exit 1
        }
    
    - name: Verify analysis outputs
      run: |
        echo "Checking for expected output files..."
        for window in 7 14 30 60 90 120 180; do
          if [ -f "backend/data/regression_results_window_${window}.json" ]; then
            echo "✓ Found regression_results_window_${window}.json"
          else
            echo "✗ Missing regression_results_window_${window}.json"
            exit 1
          fi
        done
        echo "All expected files found!"
    
    - name: Upload analysis results
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: backend/data/*.json
        retention-days: 7

  deploy:
    needs: analyze-data
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Download analysis results
      uses: actions/download-artifact@v4
      with:
        name: analysis-results
        path: frontend/data/
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './frontend'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

  cleanup:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v2
      with:
        name: |
          crypto-data
          analysis-results